import {Router} from 'express'; import Question from '../models/Question.js'; import GameSession from '../models/GameSession.js'; import User from '../models/User.js'; import {protect} from '../middleware/authMiddleware.js';
const r=Router();
const LIVES = 3;
function gradeFor(accuracy){
  if (accuracy >= 100) return { grade: 'Cyber Guardian', badge: 'Cyber Guardian' };
  if (accuracy >= 80) return { grade: 'Threat Hunter', badge: 'Threat Hunter' };
  if (accuracy >= 50) return { grade: 'Cyber Rookie', badge: 'Cyber Rookie' };
  return { grade: 'Vulnerable', badge: null };
}
r.get('/levels',protect,async(req,res,next)=>{try{const levels=await Question.aggregate([{$group:{_id:'$level',questions:{$sum:1},topics:{$addToSet:'$topic'},challenges:{$addToSet:'$challenge'}}},{$sort:{_id:1}}]);res.json({levels,lives:LIVES})}catch(e){next(e)}});
r.get('/questions/:level',protect,async(req,res,next)=>{try{const level=Number(req.params.level);if(level<1||level>5)return res.status(400).json({message:'Level must be 1-5'});const qs=await Question.find({level}).select('-correctAnswer').lean();res.json({questions:qs,lives:LIVES})}catch(e){next(e)}});
r.post('/sessions',protect,async(req,res,next)=>{try{const level=Number(req.body.level);if(level<1||level>5)return res.status(400).json({message:'Invalid level'});const s=await GameSession.create({user:req.user._id,level,livesStart:LIVES,livesLeft:LIVES});res.status(201).json({session:s,lives:LIVES,timePerQuestion:45})}catch(e){next(e)}});
r.get('/sessions/:id',protect,async(req,res,next)=>{try{const s=await GameSession.findOne({_id:req.params.id,user:req.user._id});if(!s)return res.status(404).json({message:'Attempt not found'});const done=s.status==='completed';const qs=await Question.find({level:s.level}).lean();const byId=new Map(qs.map(q=>[String(q._id),q]));const stored=s.answers||[];const detailed=stored.map(a=>{const q=byId.get(String(a.question));return {questionId:a.question,question:q?.question||'Question removed',scenario:q?.scenario,selectedAnswer:a.selectedAnswer,correctAnswer:done?q?.correctAnswer:undefined,correct:a.correct,explanation:q?.explanation||'No explanation recorded.',topic:a.topic||q?.topic,challenge:q?.challenge,points:a.points||0,maxPoints:q?.points||0}});const total=qs.length||detailed.length||0;const correctCount=s.correctCount??detailed.filter(d=>d.correct).length;const maxScore=s.maxScore||qs.reduce((t,q)=>t+(q.points||0),0)||100;const accuracy=total?Math.round((correctCount/total)*1000)/10:0;const {grade}=gradeFor(accuracy);res.json({id:s._id,level:s.level,status:s.status,score:s.score,maxScore,correctCount,total,accuracy,grade,livesLeft:s.livesLeft,livesStart:s.livesStart||LIVES,durationSeconds:s.durationSeconds||0,completedAt:s.completedAt,answers:detailed})}catch(e){next(e)}});
r.post('/sessions/:id/submit',protect,async(req,res,next)=>{try{const s=await GameSession.findOne({_id:req.params.id,user:req.user._id});if(!s)return res.status(404).json({message:'Session not found'});if(s.status==='completed')return res.status(400).json({message:'Session already completed'});const qs=await Question.find({level:s.level}).lean();const submitted=Array.isArray(req.body.answers)?req.body.answers:[];let score=0,correctCount=0;const answers=qs.map(q=>{const a=submitted.find(x=>String(x.questionId)===String(q._id));const selected=a?.selectedAnswer===undefined||a?.selectedAnswer===null?undefined:Number(a.selectedAnswer);const correct=selected===q.correctAnswer;if(correct)correctCount++;const points=correct?q.points:0;score+=points;return {question:q._id,selectedAnswer:selected,correct,topic:q.topic,points};});const maxScore=qs.reduce((t,q)=>t+(q.points||0),0)||100;const accuracy=qs.length?Math.round((correctCount/qs.length)*1000)/10:0;const livesLeft=Math.max(0,(s.livesStart||LIVES)-(qs.length-correctCount));const {grade,badge}=gradeFor(accuracy);s.answers=answers;s.score=score;s.maxScore=maxScore;s.correctCount=correctCount;s.livesLeft=livesLeft;s.status='completed';s.completedAt=new Date();const started=s.startedAt instanceof Date?s.startedAt:new Date(s.startedAt);s.durationSeconds=Math.max(0,Math.round((Date.now()-started.getTime())/1000));await s.save();const u=await User.findByIdAndUpdate(req.user._id,{$inc:{totalScore:score,gamesPlayed:1}},{new:true});let badgeEarned=null;if(badge&&!u.badges.includes(badge)){u.badges.push(badge);badgeEarned=badge;await u.save()}const detailed=qs.map(q=>{const a=answers.find(x=>String(x.question)===String(q._id));return {questionId:q._id,question:q.question,scenario:q.scenario,selectedAnswer:a?.selectedAnswer,correctAnswer:q.correctAnswer,correct:a?.correct,explanation:q.explanation,topic:q.topic,challenge:q.challenge,points:a?.points||0,maxPoints:q.points};});res.json({score,maxScore,correctCount,total:qs.length,accuracy,livesLeft,livesStart:s.livesStart||LIVES,grade,badgeEarned,durationSeconds:s.durationSeconds,answers:detailed,badges:u.badges})}catch(e){next(e)}});
export default r;
