import 'dotenv/config'; import mongoose from 'mongoose'; import connectDB from '../config/db.js'; import Question from '../models/Question.js';
const data=[
[1,'Phishing Trap','You receive an urgent email asking you to verify your bank account through a shortened link.','Phishing','phishing','What is the safest first action?',['Click and verify','Open it in incognito','Do not click; verify through the official app/site','Forward it to friends'],2,'Urgency plus a suspicious link is a common phishing pattern. Verify independently.',100],
[1,'Password Vault','A service asks you to create a password for a new account.','Password Security','password','Which choice is strongest?',['Password123!','A unique long passphrase stored in a password manager','Your birthday plus symbols','Reuse your email password'],1,'Unique, long passwords and a password manager reduce credential reuse risk.',100],
[1,'Breach Reuse','News breaks of a breach at a shop where you reused your email password.','Password Security','password','What must you do now?',['Nothing; hackers only want admins','Change that password everywhere you reused it and enable MFA','Delete the news alert','Share the password with family so they can check'],1,'Reused passwords turn one breach into many. Rotate each reuse and switch on MFA.',100],
[2,'Public Wi-Fi','You need to access sensitive work data from airport Wi-Fi.','Network Security','other','Which practice is safest?',['Use any open network','Disable device security','Use a trusted hotspot/VPN and HTTPS','Share files publicly'],2,'Avoid untrusted networks for sensitive work; use trusted connectivity and encrypted services.',100],
[2,'Malware Alert','A downloaded installer requests administrator access unexpectedly.','Malware','other','What should you do?',['Approve immediately','Cancel and verify the source/signature','Disable antivirus','Run it repeatedly'],1,'Unexpected privilege requests are a warning sign. Stop and validate the software source.',100],
[2,'Cafe Wi-Fi QR','A cafe table tent says "Scan for FREE high-speed Wi-Fi" with a QR sticker.','Fake QR Codes','qr','What is the safest move?',['Scan it; free Wi-Fi is always safe','Ask staff for the official network name and join it manually; never trust sticker codes','Enter your bank login on the landing page','Turn off your firewall first'],1,'Rogue QR codes route you through attacker hotspots that snoop traffic. Confirm the network verbally.',100],
[2,'QR Switch','A restaurant table has a QR code sticker placed over the printed menu code.','Fake QR Codes','qr','What is the safest action before scanning?',['Scan it quickly to order faster','Peel-check the sticker, ask staff, and type the official URL or use the official app','Take a photo and share it online','Disable your phone lock first'],1,'Stickers over real codes are a classic quishing trick. Verify the source before any scan.',100],
[3,'Social Engineering','A caller claims to be IT support and asks for your MFA code.','Social Engineering','other','What should you do?',['Give the code','Read only the first digits','Refuse and contact IT using a known channel','Ask for their personal number'],2,'MFA codes are secrets. Legitimate support should not ask you to disclose them.',100],
[3,'Device Defense','Your phone is lost in a public place.','Device Security','other','What is the best immediate step?',['Wait a week','Use device tracking/remote lock or erase','Post the password online','Disable the SIM only'],1,'Remote lock/erase and account-session controls can limit unauthorized access.',100],
[3,'Giveaway DM','A social-media DM from a "crypto celebrity" promises to double any coins you send.','Scam Messages','scam','What is the right call?',['Send a small test amount first','Send coins; celebrities can be trusted','Never send anything; report and block — doubling promises are always scams','Share your wallet seed phrase to verify'],2,'Doubling/celebrity-giveaway pitches are pure theft. Real figures never ask for coins.',100],
[3,'Parcel QR','You get an SMS: "Parcel held! Scan this QR to pay a $1 redelivery fee".','Fake QR Codes','qr','What should you do?',['Scan and pay the $1 immediately','Delete it, track the parcel only in the official carrier app/site','Forward your card OTP to the sender','Call back the unknown number'],1,'Delivery-fee QR lures steal cards and install malware. Always verify in the official app.',100],
[4,'Data Leak','You accidentally attach a customer spreadsheet to an external email.','Data Protection','other','What is the best response?',['Ignore it','Delete your sent folder only','Report the incident and follow the organization response process','Send another copy'],2,'Prompt reporting lets the organization contain exposure and follow legal/security procedures.',100],
[4,'Browser Security','A website displays a fake security warning telling you to install a “critical” extension.','Web Safety','other','What is the safest choice?',['Install it','Close the page and use trusted security/update channels','Call the number in the popup','Disable browser protections'],1,'Fake alerts commonly use fear to push malicious downloads or scams.',100],
[4,'Toll Smish','SMS: "Unpaid toll $4.20. Pay now or face a $50 fine: [link]". You never drive tolled roads.','Scam Messages','scam','What should you do?',['Pay fast to avoid the fine','Reply STOP and call the number','Ignore, delete, report as spam; check tolls only via the official agency site','Forward your license number to the sender'],2,'Toll smishing blasts fake fines widely. Verify only through official agency channels.',100],
[4,'Prize SMS','SMS: "You WON a $2000 gift card! Claim in 10 minutes via this link."','Scam Messages','scam','What is the safest response?',['Tap the link before it expires','Reply with your name and address to claim','Ignore/delete it and report as spam; real lotteries never demand instant link taps','Forward it to all contacts'],2,'Prize-pressure SMS links harvest personal data. Stop, report, and never tap urgently.',100],
[5,'Incident Commander','You detect multiple failed logins followed by a successful login on a sensitive account.','Incident Response','other','What should happen first?',['Delete logs','Contain the account/session and escalate according to the incident plan','Post screenshots publicly','Ignore it'],1,'Containment and escalation preserve evidence and reduce further compromise.',150],
[5,'Secure Future','Your team wants a sustainable security culture.','Security Awareness','other','Which approach is strongest?',['One annual lecture only','Continuous training, reporting, simulations and measurement','Punish every mistake','Hide incidents'],1,'Security improves when learning, reporting, simulation and measurement are continuous.',150],
[5,'Spear Phish','An email that nails your job title and boss name asks you to open an "updated org chart" attachment.','Phishing','phishing','What is the safest response?',['Open it; it knows internal details','Reply with your credentials to confirm','Verify the sender address independently and confirm via a known channel before opening','Forward it to the whole team first'],2,'Spear phishers harvest org details to look real. Details never prove legitimacy — verify out-of-band.',150],
[5,'Boss Text','A message pretending to be your CEO: "Buy 5 gift cards urgently, scratch and send codes. Keep it secret."','Scam Messages','scam','What should you do?',['Buy the cards quickly to impress the boss','Send the codes and delete the chat','Verify through a known channel and report it; executives never demand secret gift cards','Ask for more cards to be safe'],2,'CEO gift-card fraud relies on urgency plus secrecy. Always verify via a trusted channel.',150]
].map(x=>({level:x[0],title:x[1],scenario:x[2],topic:x[3],challenge:x[4],question:x[5],options:x[6],correctAnswer:x[7],explanation:x[8],points:x[9],difficulty:'medium'}));
await connectDB(); await Question.deleteMany({}); await Question.insertMany(data); console.log(`Seeded ${data.length} questions`); await mongoose.disconnect();
